name: login_t1_package
description: "A new Flutter package project."
version: 1.1.1
homepage: https://github.com/thunyalukfern/login_t1_package.git

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
